var Deities = [
	"DEITY_AVANDRA",
	"DEITY_BAHAMUT",
	"DEITY_CORELLON",
	"DEITY_ERATHIS",
	"DEITY_IOUN",
	"DEITY_KORD",
	"DEITY_MELORA",
	"DEITY_MORADIN",
	"DEITY_PELOR",
	"DEITY_RAVEN_QUEEN",
	"DEITY_SEHANINE",
	"DEITY_ASMODEUS",
	"DEITY_BANE",
	"DEITY_GRUUMSH",
	"DEITY_LOLTH",
	"DEITY_TIAMAT",
	"DEITY_TOROG",
	"DEITY_VECNA",
	"DEITY_ZEHIR",
];

var Sizes = [
	"SIZE_MEDIUM",
	"SIZE_SMALL"
];

var Genders= [
	"GENDER_MALE",
	"GENDER_FEMALE"	
];

var Alignments = [
	"ALIGNMENT_UNALIGNED",
	"ALIGNMENT_GOOD",
	"ALIGNMENT_LAWFUL_GOOD",
	"ALIGNMENT_EVIL",
	"ALIGNMENT_CHAOTIC_EVIL",
];